name: your-first-workflow
on: [push]
jobs:
        check-dependencies:
                runs-on: ubuntu-latest
                steps:
                        - uses: action/setup-node
                        - run: python --version
                        - run: python -c "import numpy as np; print(np.__version__)"
